const db = require('../../../database/db');

// Mapping Table Schemas (Derived from sheet columns)
const TABLE_SCHEMAS = {
    "CHCData": ["lead_source", "state", "address", "pincode", "customer_email", "customer_added_by", "lead_generated_by", "calling_date", "calling_time", "call_connect", "region_type", "average_bill_amount", "required_plant_capacity", "required_per_day_unit", "type_of_solar_plant", "how_many_ac_do_you_have", "do_you_want_finance", "in_which_bank_you_have_account", "do_you_want_site_visit", "customers_comment_on_call", "chc_associate_remark", "need_call_followup", "followup_plan_date", "customer_lead_status", "assign_to_site_visit", "customer_meeting_plan_date", "end_meeting_date", "start_meeting_time", "meeting_creator", "current_lead_status", "related_followups"],
    "ConvertBooking": ["lead_source", "address", "lead_generated_by", "calling_date", "type_of_solar_plant", "customers_comment_on_call", "associate_remark", "customer_lead_status", "assign_to_site_visit", "convert_into_booking", "site_visit_date", "site_visit_customers_comment", "customers_address_location", "roof_size_sqft", "notes_on_roof_area", "solar_project_owner_person_name", "register_mobile_number", "email_id", "age", "name_transfer_require", "current_section_load_kw", "load_increment_require", "panel_type", "inverter_size", "structure_type", "extra_cost", "rsolar_kit_remark", "solar_plant_price", "purchase_type", "cibil_score", "loan_tenure_year", "bank_account_name", "branch_name", "running_any_home_loan", "home_loan_bank_name", "comment_on_finance", "aadhaar_number", "pan_number", "booking_documentation_done", "nameplate_1st_line", "nameplate_2nd_line", "assign_name_plate_for_print", "booking_comment", "assign_for_agreement_process", "aadhaar_name_english", "customer_aadhaar_number", "aadhaar_address_english", "aadhaar_so_english", "aadhaar_front_full_text", "aadhaar_back_full_text", "dob", "gender", "pan_card_fileid", "customer_pan_number", "income_proof_title", "load_increment_extra_cost", "inverter_extra_cost", "convert_into_booking_date", "required_load", "changes_in_price_after_inspection", "loan_difference_amount", "load_increment_extra_cost_received", "inverter_extra_cost_received", "changes_in_price_after_inspection_received", "loan_difference_amount_received", "management_discount", "solar_plant_mrp_price", "sales_assigned_to_mobile_number", "payment_received_amount", "pending_solar_payment", "cancel_request_reason", "cancel_request_date", "request_for_cancel", "pending_extra_amount", "leegality_test"],
    "backend_fid": ["lead_source", "lead_generated_by", "assign_to_site_visit", "convert_into_booking", "site_visit_date", "site_visit_customers_comment", "solar_project_owner_person_name", "register_mobile_number", "email_id", "age", "name_transfer_require", "current_section_load_kw", "load_increment_require", "panel_type", "solar_plant_price", "purchase_type", "cibil_score", "loan_tenure_year", "bank_account_name", "branch_name", "running_any_home_loan", "home_loan_bank_name", "comment_on_finance", "adhar_number", "pan_number", "current_section_load_kw_41", "load_increment_require_42", "booking_documentation_done", "nameplate_1st_line", "nameplate_2nd_line", "assign_name_plate_for_print", "booking_comment", "assign_for_agreement_process", "customer_file_number", "create_file", "create_agreement", "agreement_number", "agreement_created_date", "agreement_created_by", "assign_file_for_signature", "assign_date", "assign_to_file_for_signature", "signature_file_received", "file_receiving_date", "file_receiving_by", "apply_for_subsidy", "subsidy_bank_name", "application_reference_number", "apply_on_jansamarth", "loan_amount", "selected_bank_for_loan", "loan_apply_branch_name", "online_portal_apply_status", "online_portal_apply_remark", "online_portal_apply_date", "online_portal_apply_by", "frontaadhaarfileid", "backaadhaarfileid", "username", "aadhaarno", "address", "careof", "load_increment_extra_cost", "inverter_extra_cost", "convert_into_booking_date", "jansamarth_comment", "subsidy_comment", "payment_received_status", "comment", "document_collected", "document_collected_date", "document_collected_by", "subsidy_registration_date", "apply_on_jsp_or_ecofy", "apply_on_jsp_or_ecofy_date", "apply_on_jsp_or_ecofy_by", "required_load", "name_transfer_date", "quotation_amount", "solar_plant_mrp_price", "nondcr_portal_registration_number", "leegality_test"],
    "Site_visit": ["lead_source", "address", "lead_generated_by", "calling_date", "type_of_solar_plant", "customers_comment_on_call", "associate_remark", "customer_lead_status", "assign_to_site_visit", "customer_meeting_plan_date", "calling_date_for_visit", "customers_comment_for_visit", "site_visit_plan_date", "site_visit_plan_time", "ready_for_visit", "site_visit_date", "site_visit_customers_comment", "customers_address_location", "roof_size_sqft", "notes_on_roof_area", "solar_project_owner_person_name", "register_mobile_number", "email_id", "age", "name_transfer_require", "current_section_load_kw", "load_increment_require", "panel_type", "solar_plant_price", "purchase_type", "cibil_score", "loan_tenure_year", "bank_account_name", "branch_name", "convert_into_booking", "reasons_of_maybe", "next_visit_plan_date", "sitevisitfollowupdate", "inverter_size", "load_increment_extra_cost", "inverter_extra_cost", "why_is_name_transfer_needed", "name_transfer_comment", "required_load", "customer_site_visit_follow_up", "solar_plant_mrp_price"],
    "backend_main": ["lead_source", "lead_generated_by", "assign_to_site_visit", "convert_into_booking", "site_visit_date", "site_visit_customers_comment", "solar_project_owner_person_name", "register_mobile_number", "email_id", "age", "name_transfer_require", "current_section_load_kw", "load_increment_require", "panel_type", "solar_plant_price", "purchase_type", "cibil_score", "loan_tenure_year", "bank_account_name", "branch_name", "running_any_home_loan", "home_loan_bank_name", "comment_on_finance", "adhar_number", "pan_number", "current_section_load_kw_41", "load_increment_require_42", "booking_documentation_done", "nameplate_1st_line", "nameplate_2nd_line", "assign_name_plate_for_print", "booking_comment", "assign_for_agreement_process", "customer_file_number", "create_file", "create_agreement", "agreement_number", "agreement_created_date", "agreement_created_by", "assign_file_for_signature", "assign_date", "assign_to_file_for_signature", "signature_file_received", "file_receiving_date", "file_receiving_by", "apply_for_subsidy", "subsidy_bank_name", "application_reference_number", "apply_on_jansamarth", "loan_amount", "selected_bank_for_loan", "loan_apply_branch_name", "online_portal_apply_status", "online_portal_apply_remark", "online_portal_apply_date", "online_portal_apply_by", "frontaadhaarfileid", "backaadhaarfileid", "username", "aadhaarno", "address", "careof", "load_increment_extra_cost", "inverter_extra_cost", "convert_into_booking_date", "jansamarth_comment", "subsidy_comment", "payment_received_status", "comment", "document_collected", "document_collected_date", "document_collected_by", "subsidy_registration_date", "apply_on_jsp_or_ecofy", "apply_on_jsp_or_ecofy_date", "apply_on_jsp_or_ecofy_by", "required_load", "name_transfer_date", "quotation_amount", "solar_plant_mrp_price", "nondcr_portal_registration_number", "extra_cost", "approved_loan_amount", "bank_branch_valid", "agreement_signed_status_leegality"],
    "NameTransfer": ["lead_source", "lead_generated_by", "assign_to_site_visit", "convert_into_booking", "site_visit_date", "site_visit_customers_comment", "solar_project_owner_person_name", "register_mobile_number", "name_transfer_require", "current_section_load_kw", "load_increment_require", "panel_type", "adhar_number", "collect_name_transfer_file", "file_receving_date_by_sales_team", "apply_for_name_transfer", "name_transfer_file_submission_date", "comment_on_name_transfer", "name_transfer_mpeb_charges_paid_by_r_solar", "charges_paid_by_customers", "charges_paid_by_rsolar", "name_transfer_status", "name_transfer_date", "ready_for_online_portal", "receipt_for_name_transfer", "name_transfer_completed_date", "file_receiving_date", "document_collected"],
    "Banking": ["lead_source", "lead_generated_by", "assign_to_site_visit", "solar_project_owner_person_name", "register_mobile_number", "panel_type", "system_cost", "adhar_number", "pan_number", "apply_on_jansamarth", "loan_amount", "selected_bank_for_loan", "loan_apply_branch_name", "online_portal_apply_status", "online_portal_apply_remark", "online_portal_apply_date", "online_portal_apply_by", "create_banking_file", "assign_to_file_for_submission", "file_submitted_into_bank", "file_bank_submission_date", "file_bank_submission_by", "banking_loan_comment", "margin_money_require", "margin_money_amount", "deposit_margin_money", "margin_money_deposit_date", "current_loan_status_comment", "comment_update_date", "payment_received_status", "payment_received_date", "payment_received_amount", "bank_name", "utr_reference", "col_1st_payment_confirmation", "col_1st_payment_finance_remark", "col_1st_payment_finance_update_date", "partial_payment_received_date", "partial_payment_received_amount", "partial_amount_received_bank_name", "partial_amount_utr_reference", "col_3rd_payment_received_date", "col_3rd_payment_received_amount", "col_3rd_amount_received_bank_name", "col_3rd_amount_utr_reference", "total_amount_received", "pending_solar_payment", "partial_payment_confirmation", "partial_payment_remark", "partial_payment_date", "approved_loan_amount", "pending_amount", "margin_type", "second_margin_money_required", "second_margin_money_amount", "second_margin_money_date", "load_increment_extra_cost", "load_increment_extra_cost_received", "inverter_extra_cost", "inverter_extra_cost_received", "col_1st_ecofy_payment_amount", "col_1st_ecofy_payment_date", "col_2nd_ecofy_payment_amount", "col_2nd_ecofy_payment_date", "financing_extra_cost", "financing_extra_cost_receiving_date", "file_assigned_to", "apply_on_jsp_or_ecofy", "changes_in_price_after_inspection", "changes_in_price_after_inspection_received", "not_approved_amount", "remaining_extra_amount_date", "remaining_extra_amount_by", "management_discount", "loan_difference_amount", "loan_difference_amount_received", "li_extra_cost_received_utr_and_reference", "inverter_extra_cost_received_utr_and_reference", "changes_in_price_after_inspection_received_utr_and_reference", "loan_difference_amount_received_utr_and_reference", "create_banking_file_date", "file_receiving_date", "apply_on_jsp_or_ecofy_date", "quotation_amount", "first_margin_money_utr_reference", "second_margin_money_utr_reference", "approved_loan_amount_3", "pending_extra_amount", "bank_branch_valid", "signature_file_received"],
    "PreInspection": ["lead_source", "lead_generated_by", "assign_to_site_visit", "solar_project_owner_person_name", "register_mobile_number", "panel_type", "inverter_size", "customers_address_location", "roof_size_sqft", "notes_on_roof_area", "create_3d_model", "col_3d_model_remark", "col_3d_model_date", "created_by", "handover_3d_model_to_customer", "take_signature_on_3d_model", "presite_inspection_status", "assign_to_site_spection", "spection_date_plan", "roof_site_installation_comment", "inverter_location_comment", "invertor_distance_from_structure", "earthing_location_image", "earthing_location_distance_from_panel", "site_inspection_comments", "site_inspection_date", "site_inspection_by", "final_structure_type", "changes_in_structure_ft", "other_changes", "changes_in_price_after_inspection", "create_boq", "payment_received_status", "payment_received_amount", "payment_received_date", "presite_visit_inspection_required", "presite_visit_inspection_status", "presite_visit_inspection_status_completed_date", "col_3d_model_status", "col_3d_model_status_complete_date", "agreement_date", "section_1_presite_inspection", "section_2_3d_model", "section_3_bill_of_quantity_boq"],
    "Delivery": ["lead_source", "lead_generated_by", "assign_to_site_visit", "panel_type", "system_cost", "payment_received_status", "payment_received_date", "payment_received_amount", "bank_name", "utr_reference", "placed_solar_order", "order_id", "invoice_order_date", "number_of_pannels", "pannel_serial_numbers", "invertor_type", "invertor_serial_numbers", "strucute_type", "solar_kit_item", "ready_for_dispatch", "delivery_scheduled", "delivery_schedule_date", "delivery_schedule_comment", "delivery_status", "delivery_date", "delivery_comment", "delivery_by", "installation_scheduled", "assign_to_site_for_installation", "installation_schedule_date", "installation_schedule_comment", "instatllation_status", "installation_date", "any_installation_pendancy", "installation_comment", "installation_status_update_by", "assign_to_civil_work", "schedule_date_civil_work", "assign_by_civil_work", "cc_block_status", "completed_by_civil_work", "cc_block_comment", "cc_block_completed_date", "ss_plate_installed", "ss_plate_installed_by", "ss_plate_installation_date", "progress_status", "solar_order_process_status", "solar_order_process_date", "solar_order_process_by", "loan_difference_amount", "loan_difference_amount_received", "load_increment_extra_cost", "load_increment_extra_cost_received", "changes_in_price_after_inspection", "changes_in_price_after_inspection_received", "inverter_extra_cost", "inverter_extra_cost_received", "management_discount", "approved_loan_amount", "section_1_ready_for_installation", "section_2_installation_process", "section_3_ss_installation", "pending_extra_amount", "auto_order_id", "has_zoho_order"],
    "LoadChange": ["lead_source", "lead_generated_by", "assign_to_site_visit", "convert_into_booking", "site_visit_date", "site_visit_customers_comment", "solar_project_owner_person_name", "register_mobile_number", "name_transfer_require", "current_section_load_kw", "load_increment_require", "panel_type", "adhar_number", "payment_received", "mpeb_load_change_file_creation", "load_change_file_documents_list", "required_load", "load_change_charge", "load_change_file_submitted_into_mpeb", "payment_submitted_into_mpeb", "load_change_comment", "paid_by_farmkart", "paid_by_customers", "load_change_file_submission_date", "load_change_file_submission_by", "load_change_status", "load_change_date", "progress_status", "required_load_by_sales_dept", "load_increment_extra_cost", "load_change_completed_date"],
    "WCR": ["lead_source", "lead_generated_by", "assign_to_site_visit", "solar_project_owner_person_name", "register_mobile_number", "panel_type", "system_cost", "adhar_number", "payment_received_status", "payment_received_date", "payment_received_amount", "application_reference_number", "order_id", "invoice_order_date", "delivery_status", "installation_status", "number_of_pannels", "pannel_serial_numbers", "invertor_type", "invertor_serial_numbers", "create_dcr_certificate", "dcr_creation_date", "dcr_crtificate_created_by", "create_demant_note", "submitted_feasibility_report_into_division_office", "collect_demand_id_from_division", "customers_demand_id", "collect_payment_from_rsolar_account_for_demand_note", "apply_for_meter_order_into_mpeb", "online_portal_charges_pay", "online_portal_apply_date", "online_demand_apply_by", "collect_500_rs_stamp_on_customer_name", "stamp_receiving_date", "create_work_completion_report", "attached_document_into_wcr_report", "assigned_wcr_file_for_customers_signature", "assigned_to_file", "customers_signature_done_on_wcr_file", "collect_payment_from_rsolar_account_for_mpeb_division", "total_amount_received", "amount_received_date", "submitted_file_for_je_verification", "file_submitssion_date_into_je", "collect_wcr_file_from_je_office", "collect_wcr_file_from_je_office_date", "submitted_file_for_de_verification", "submitted_file_date_for_de_verificaton", "collect_meter_approval_letter_for_de_office", "assigned_meter_to_meter_installer_person", "connect_with_customer_for_meter_installation", "meter_installation_status", "meter_installation_date", "collect_old_meter_from_customer_house", "create_disposal_report_with_customer_signature", "submitted_old_meter__disposal_report_into_dc_office", "mpeb_process_status", "wifi_available_at_customers_site", "software_connection_status", "software_conection_date", "system_handover", "stamp_receiving_by", "create_wcr_date", "create_wcr_by", "assigned_by_file_date", "meter_installation_by", "demand_note_creation_date", "submitted_file_for_je_verificationdate", "received_signature_submitted_file_for_je_verification", "received_signature_submitted_file_for_je_verification_date", "collect_meter_approval_letter_for_de_office_date", "delivery_date", "installation_date", "section_3__je_verification", "section_4__de_verification", "section_5__meter_installation", "panel_serials", "inverter_serial"],
    "handover": ["lead_source", "lead_generated_by", "assign_to_site_visit", "panel_type", "system_cost", "payment_received_status", "payment_received_date", "payment_received_amount", "bank_name", "utr_reference", "number_of_panels", "panel_serial_numbers", "inverter_type", "inverter_serial_numbers", "structure_type", "delivery_date", "delivery_comment", "assign_to_site_for_installation", "installation_status", "installation_date", "any_installation_pendancy", "installation_comment", "cc_block_status", "cc_block_comment", "cc_block_completed_date", "ss_plate_installed", "ss_plate_installed_by", "ss_plate_installation_date", "inspection_scheduled", "inspection_date_plan", "inspection_assign_to", "inspection_date", "post_inspection_status", "any_issue", "issue_descriptions", "inspection_comment", "system_handover", "customer_feedback", "subsidy_apply_status", "subsidy_apply_date", "subsidy_apply_comment", "subsidy_apply_by", "subsidy_redemption_status", "subsidy_redemption_reference_number", "subsidy_redemption_date", "subsidy_redemption_comment", "subsidy_redemption_by", "subsidy_received", "subsidy_received_check_date", "progress_status", "create_dcr_certificate", "submitted_file_for_je_verification", "submitted_file_for_de_verification", "create_banking_file_date", "meter_installation_date", "submitted_file_date_for_de_verificaton"]
};

// Utils
const toSqlName = (col) => {
    let name = col.trim().replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '').toLowerCase();
    if (/^[0-9]/.test(name)) name = 'col_' + name;
    return name;
};

/**
 * Sync logic for Mission Control Data
 */
const syncMissionControlData = async (req, res) => {
    const { data } = req.body;
    if (!data || !Array.isArray(data)) {
        return res.status(400).json({ status: 'error', message: "Invalid data format. Expected { data: [...] }" });
    }

    const trx = await db.transaction();
    try {
        for (const row of data.slice(0, 2)) {
            const mobileNo = row['Mobile No'] || row['mobile_no'] || row['register_mobile_number'];
            if (!mobileNo) continue; // Skip rows without mobile number (join key)

            // 1. Resolve customerId from 'customerDetails' table
            // We use 'like' with the last 10 digits to be flexible with country code variations
            const cleanMobile = mobileNo.toString().replace(/\D/g, '');
            const last10 = cleanMobile.slice(-10);

            if (last10.length < 10) {
                console.warn(`[Sync] Skipping invalid mobile number: ${mobileNo}`);
                continue;
            }

            const customer = await trx('customerDetails')
                .select('customerId')
                .where('mobileNumber', 'like', `%${last10}%`)
                .first();

            if (!customer) {
                console.log(`[Sync] Mobile ${mobileNo} NOT found in customerDetails. Skipping.`);
                continue;
            }

            const customerId = customer.customerId;

            // 2. Distribute columns to all 12 tables
            for (const tableName of Object.keys(TABLE_SCHEMAS)) {
                const allowedCols = TABLE_SCHEMAS[tableName];
                const insertData = { customerId, mobile_no: mobileNo };
                let hasData = false;

                // Map row fields to table columns
                for (const sheetKey of Object.keys(row)) {
                    const sqlCol = toSqlName(sheetKey);
                    if (allowedCols.includes(sqlCol)) {
                        insertData[sqlCol] = row[sheetKey];
                        hasData = true;
                    }
                }

                if (hasData) {
                    // UPSERT logic using Knex
                    // Note: mobile_no or customerId should have a UNIQUE index for onConflict to work correctly.
                    await trx(tableName)
                        .insert(insertData)
                        .onConflict('mobile_no')
                        .merge();
                }
            }
        }

        await trx.commit();
        res.status(200).json({ status: 'success', message: `Successfully synced ${data.length} rows.` });
    } catch (error) {
        await trx.rollback();
        console.error("Sync Error:", error);
        res.status(500).json({ status: 'error', message: "Sync Failed: " + error.message });
    }
};

module.exports = {
    syncMissionControlData
};
